repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6
  - repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.8.3
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.5.2
    hooks:
    - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-merge-conflict
    - id: fix-encoding-pragma
      args: ["--remove"]
    - id: mixed-line-ending
      args: ["--fix=lf"]
